  LogLevel: "debug"
  port: 9096
  driver: "mysql"
  connection: "root:kXbXt2nLrL@tcp(localhost:3306)/idx?&parseTime=true"
  privatekeypath: "../certs/rsa_pri.key"
  publickeypath: "../certs/rsa_pub.pem"
  httpscheme: "http"
  RedisHost: "localhost"
  RedisPort: 30248
  RedisDB: 0